trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

jobs:
- job: setupProtobuffs
  steps:
  - script: curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip && unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
    displayName: 'Get Protobuffs'
    condition: succeeded()

  - script: sudo mv protoc3/bin/* /usr/local/bin/ && sudo mv protoc3/include/* /usr/local/include/ && ls -la /usr/local/bin
    displayName: 'Intall Protobuffs'
    condition: succeeded()

  - script: sudo chown root /usr/local/bin/protoc && sudo chown -R root /usr/local/include/google && ls -la /usr/local/bin
    displayName: 'Set permissions'
    condition: succeeded()
- job: installRust
  steps:
  - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
    displayName: 'Install rustup toolchain'
- job: setupLerna
  steps:
  - script: npm install lerna
    displayName: 'Install lerna'

  - script: lerna bootstrap
    displayName: 'Run lerna bootstrap'
  
  - script: lerna run build
    displayName: 'Run lerna build'
